/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IntegrateRouteImport } from './routes/integrate'
import { Route as OrderCompleteRouteImport } from './routes/order-complete'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as ApiPublicCheckoutSessionsRouteImport } from './routes/api/public/checkout/sessions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrateRoute = IntegrateRouteImport.update({
  id: '/integrate',
  path: '/integrate',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteRoute = OrderCompleteRouteImport.update({
  id: '/order-complete',
  path: '/order-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutSessionsRoute =
  ApiPublicCheckoutSessionsRouteImport.update({
    id: '/api/public/checkout/sessions',
    path: '/api/public/checkout/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/integrate': typeof IntegrateRoute
  '/order-complete': typeof OrderCompleteRoute
  '/pay/$id': typeof PayIdRoute
  '/api/public/checkout/sessions': typeof ApiPublicCheckoutSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/integrate': typeof IntegrateRoute
  '/order-complete': typeof OrderCompleteRoute
  '/pay/$id': typeof PayIdRoute
  '/api/public/checkout/sessions': typeof ApiPublicCheckoutSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/integrate': typeof IntegrateRoute
  '/order-complete': typeof OrderCompleteRoute
  '/pay/$id': typeof PayIdRoute
  '/api/public/checkout/sessions': typeof ApiPublicCheckoutSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/integrate'
    | '/order-complete'
    | '/pay/$id'
    | '/api/public/checkout/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/integrate'
    | '/order-complete'
    | '/pay/$id'
    | '/api/public/checkout/sessions'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/integrate'
    | '/order-complete'
    | '/pay/$id'
    | '/api/public/checkout/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  IntegrateRoute: typeof IntegrateRoute
  OrderCompleteRoute: typeof OrderCompleteRoute
  PayIdRoute: typeof PayIdRoute
  ApiPublicCheckoutSessionsRoute: typeof ApiPublicCheckoutSessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrate': {
      id: '/integrate'
      path: '/integrate'
      fullPath: '/integrate'
      preLoaderRoute: typeof IntegrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete': {
      id: '/order-complete'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout/sessions': {
      id: '/api/public/checkout/sessions'
      path: '/api/public/checkout/sessions'
      fullPath: '/api/public/checkout/sessions'
      preLoaderRoute: typeof ApiPublicCheckoutSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  IntegrateRoute: IntegrateRoute,
  OrderCompleteRoute: OrderCompleteRoute,
  PayIdRoute: PayIdRoute,
  ApiPublicCheckoutSessionsRoute: ApiPublicCheckoutSessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
